# Generated by Django 4.1.1 on 2024-08-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('year_of_foundation', models.IntegerField(blank=True, null=True)),
                ('registered_office', models.CharField(default='Unknown Office', max_length=255)),
                ('registered_office_city', models.CharField(default='Unknown City', max_length=255)),
                ('executive_year_of_change', models.IntegerField(blank=True, default=0, null=True)),
                ('executive_change_count', models.IntegerField(blank=True, default=0, null=True)),
                ('employee_count', models.IntegerField(blank=True, default=0, null=True)),
                ('revenue_year', models.IntegerField(blank=True, default=0, null=True)),
                ('YoY_increase_in_sales', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_name', models.CharField(max_length=255)),
                ('executive_address', models.CharField(max_length=255)),
                ('executive_city', models.CharField(default='Unknown City', max_length=255)),
                ('executive_year_of_change', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_office', models.CharField(max_length=255)),
                ('registered_office_city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_year', models.IntegerField(default=0)),
                ('YoY_increase_in_sales', models.IntegerField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='viewer.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.IntegerField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='viewer.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_office_debt', models.IntegerField(default=0)),
                ('social_insurance_agency_debt', models.IntegerField(default=0)),
                ('health_insurance_company_debt', models.IntegerField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='viewer.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='viewer.executive'),
        ),
    ]
