# Generated by Django 4.1.1 on 2024-08-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydebt',
            name='health_insurance_company_debt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='companydebt',
            name='social_insurance_agency_debt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='companydebt',
            name='tax_office_debt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='registeredoffice',
            name='registered_office_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registeredoffice',
            name='registered_office_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='YoY_increase_in_sales',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='revenue_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
