# Generated by Django 4.1.1 on 2024-06-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('date_of_change', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='date_of_foundation',
            field=models.DateField(null=True),
        ),
    ]
