# Generated by Django 4.1.1 on 2024-08-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_companydebt_health_insurance_company_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='executive_change_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
