# Generated by Django 4.1.1 on 2024-08-01 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_executive_company_date_of_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AddField(
            model_name='company',
            name='YoY_increase_in_sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='viewer.executive'),
        ),
        migrations.AddField(
            model_name='company',
            name='executive_change_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='executive_year_of_change',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='health_insurance_company_debt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_office',
            field=models.CharField(default='Unknown Office', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_office_city',
            field=models.CharField(default='Unknown City', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='social_insurance_agency_debt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_office_debt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='city',
            field=models.CharField(default='Unknown City', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_foundation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='executive',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='executive',
            name='date_of_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_revenue', models.IntegerField(default=0)),
                ('year', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='viewer.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='viewer.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_office_debt', models.IntegerField(default=0)),
                ('social_insurance_debt', models.IntegerField(default=0)),
                ('health_insurance_debt', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='viewer.company')),
            ],
        ),
    ]
