# Generated by Django 4.1.1 on 2024-08-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_company_executive_change_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='executive_change_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='executive_year_of_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_of_foundation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companydebt',
            name='health_insurance_company_debt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companydebt',
            name='social_insurance_agency_debt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companydebt',
            name='tax_office_debt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registeredoffice',
            name='registered_office_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registeredoffice',
            name='registered_office_city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='YoY_increase_in_sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='revenue_year',
            field=models.IntegerField(),
        ),
    ]
