# Generated by Django 4.1.1 on 2024-08-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_company_executive_change_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='executive_city',
            field=models.CharField(max_length=255),
        ),
    ]
