# Generated by Django 4.1.1 on 2024-08-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
