# Generated by Django 4.1.1 on 2024-08-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('employee_count', models.IntegerField()),
                ('YoY_increase_in_sales', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.CreateModel(
            name='CompanyDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_office_debt', models.IntegerField(default=0)),
                ('social_insurance_agency_debt', models.IntegerField(default=0)),
                ('health_insurance_company_debt', models.IntegerField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='accounts.company')),
            ],
        ),
    ]
